/* CAFFE MINI - Website quản lý bán hàng kết nối PHP + MySQL */
const API_BASE="api";
const CART_KEY="cm_cart_session_v2";
const BANK_KEY="cm_bank_device_v2";
const state={currentUser:null,csrfToken:"",products:[],orders:[],users:[],reviews:[],editingOrderId:null};

function clone(v){return JSON.parse(JSON.stringify(v));}
function formatMoney(n){return Number(n||0).toLocaleString("vi-VN")+"đ";}
function escapeHtml(s=""){return String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#039;",'"':"&quot;"}[c]));}
function fmtDate(v){if(!v)return"-";const d=new Date(String(v).replace(" ","T"));return Number.isNaN(d.getTime())?String(v):d.toLocaleString("vi-VN");}

async function apiRequest(path,options={}){
  const method=(options.method||"GET").toUpperCase();
  const headers={Accept:"application/json",...(options.headers||{})};
  if(options.body&&!headers["Content-Type"])headers["Content-Type"]="application/json";
  if(!["GET","HEAD","OPTIONS"].includes(method)&&state.csrfToken)headers["X-CSRF-Token"]=state.csrfToken;
  const response=await fetch(`${API_BASE}/${path}`,{...options,method,headers,credentials:"same-origin"});
  let data;try{data=await response.json();}catch{throw new Error("Máy chủ trả về dữ liệu không hợp lệ.");}
  if(!response.ok||data.ok===false)throw new Error(data.message||`Lỗi máy chủ ${response.status}`);
  if(data.csrfToken)state.csrfToken=data.csrfToken;
  return data;
}
async function refreshCoreData(){const d=await apiRequest("bootstrap.php");state.currentUser=d.currentUser||null;state.csrfToken=d.csrfToken||state.csrfToken;state.products=d.products||[];state.orders=d.orders||[];state.users=d.users||[];state.reviews=d.reviews||[];return d;}
function showSystemError(message){const b=document.createElement("div");b.className="system-fatal";b.innerHTML=`<div><i class="fa-solid fa-triangle-exclamation"></i><b>Không thể kết nối hệ thống</b><span>${escapeHtml(message)}</span><small>Kiểm tra Apache, MySQL và database <b>caffe_mini</b> rồi tải lại trang.</small></div>`;document.body.prepend(b);}
async function bootPage(page){try{await refreshCoreData();renderCommonNav();initAiChatWidget();if(page==="home")initHome();else if(page==="login")initLogin();else if(page==="register")initRegister();else if(page==="sell")initSell();else if(page==="profile")initProfile();else if(page==="admin")initAdmin();}catch(e){console.error(e);showSystemError(e.message);}}
function showToast(message,type="success"){const a=document.getElementById("toastArea");if(!a){alert(message);return;}const id="t"+Date.now(),cls=type==="error"?"text-bg-danger":type==="warning"?"text-bg-warning":type==="info"?"text-bg-info":"text-bg-success";a.insertAdjacentHTML("beforeend",`<div id="${id}" class="toast show ${cls} cm-toast"><div class="d-flex"><div class="toast-body">${escapeHtml(message)}</div><button class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"></button></div></div>`);setTimeout(()=>document.getElementById(id)?.remove(),3200);}
function routeFor(u){return u?.role==="admin"?"admin.html":"sell.html";}
function requireLogin(roles=[]){const u=state.currentUser;if(!u||u.active===false||(roles.length&&!roles.includes(u.role))){location.href="login.html";return null;}return u;}
function renderCommonNav(){const u=state.currentUser,by=id=>document.getElementById(id);if(by("navLoginItem"))by("navLoginItem").classList.toggle("d-none",!!u);if(by("navLogoutItem"))by("navLogoutItem").classList.toggle("d-none",!u);if(by("navProfileItem"))by("navProfileItem").classList.toggle("d-none",!u);if(by("navSellItem"))by("navSellItem").classList.toggle("d-none",!u);if(by("navAdminItem"))by("navAdminItem").classList.toggle("d-none",!(u&&u.role==="admin"));document.querySelectorAll("#logoutBtn").forEach(btn=>btn.onclick=async e=>{e.preventDefault();try{await apiRequest("auth.php",{method:"POST",body:JSON.stringify({action:"logout"})});}catch{}sessionStorage.removeItem(CART_KEY);location.href="login.html";});}

function initLogin(){if(state.currentUser){location.href=routeFor(state.currentUser);return;}const f=document.getElementById("loginForm");f.addEventListener("submit",async e=>{e.preventDefault();const btn=f.querySelector("button[type=submit]");btn.disabled=true;try{const r=await apiRequest("auth.php",{method:"POST",body:JSON.stringify({action:"login",id:document.getElementById("loginUser").value.trim(),password:document.getElementById("loginPass").value})});state.currentUser=r.user;showToast("Đăng nhập thành công");setTimeout(()=>location.href=routeFor(r.user),300);}catch(err){showToast(err.message,"error");}finally{btn.disabled=false;}});}
function initRegister(){if(state.currentUser){location.href=routeFor(state.currentUser);return;}document.getElementById("registerForm").addEventListener("submit",async e=>{e.preventDefault();const p={action:"register",username:document.getElementById("regUsername").value.trim(),email:document.getElementById("regEmail").value.trim(),password:document.getElementById("regPass").value,fullName:document.getElementById("regName").value.trim(),phone:document.getElementById("regPhone").value.trim()};try{const r=await apiRequest("auth.php",{method:"POST",body:JSON.stringify(p)});showToast(r.message||"Đăng ký thành công");setTimeout(()=>location.href="login.html",500);}catch(err){showToast(err.message,"error");}});}

function productCategories(){return[...new Set(state.products.filter(p=>p.active!==false).map(p=>p.category))].sort();}
function fillCategories(id){const s=document.getElementById(id);if(!s)return;s.innerHTML='<option value="all">Tất cả danh mục</option>'+productCategories().map(c=>`<option value="${escapeHtml(c)}">${escapeHtml(c)}</option>`).join("");}
function placeholder(name,cat){const c=cat==="Cà phê"?"6f4e37":cat==="Trà"?"d97706":cat==="Trà sữa"?"b08968":cat==="Nước ép"?"f59e0b":cat==="Đồ ăn kèm"?"92400e":"ea580c";return`data:image/svg+xml;charset=UTF-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="400"><rect width="100%" height="100%" fill="#${c}"/><circle cx="300" cy="165" r="88" fill="#fff" opacity=".18"/><path d="M235 115 h130 l-12 160 h-106z" fill="#fff" opacity=".85"/><text x="300" y="350" text-anchor="middle" font-family="Arial" font-size="30" fill="#fff" font-weight="bold">${name}</text></svg>`)}`;}
function imageSrc(p){return p.image?.trim()||placeholder(p.name,p.category);}
function renderHomeProducts(){const list=document.getElementById("productList");if(!list)return;const q=(document.getElementById("searchInput")?.value||"").trim().toLowerCase(),cat=document.getElementById("filterCategory")?.value||"all";const ps=state.products.filter(p=>p.active!==false&&p.name.toLowerCase().includes(q)&&(cat==="all"||p.category===cat));list.innerHTML=ps.map(p=>`<div class="col-sm-6 col-md-4 col-xl-3 fade-in"><div class="card product-card premium-product-card"><div class="product-image-wrap"><img src="${imageSrc(p)}" alt="${escapeHtml(p.name)}"><span class="product-price-float">${formatMoney(p.price)}</span></div><div class="card-body d-flex flex-column"><span class="badge badge-category align-self-start mb-2">${escapeHtml(p.category)}</span><h5 class="product-name">${escapeHtml(p.name)}</h5><p class="desc">${escapeHtml(p.desc||"")}</p><button class="btn product-detail-btn mt-auto" onclick="showProductDetail(${p.id})"><span>Xem chi tiết</span><i class="fa-solid fa-arrow-right"></i></button></div></div></div>`).join("")||'<div class="col-12"><div class="empty-state"><h5>Không tìm thấy món</h5></div></div>';}
function showProductDetail(id){const p=state.products.find(x=>x.id===id);if(!p)return;document.getElementById("detailBody").innerHTML=`<div class="row g-3"><div class="col-md-5"><img src="${imageSrc(p)}" class="img-fluid rounded"></div><div class="col-md-7"><h3>${escapeHtml(p.name)}</h3><p><span class="badge bg-warning text-dark">${escapeHtml(p.category)}</span></p><h4 class="text-danger">${formatMoney(p.price)}</h4><p>${escapeHtml(p.desc||"")}</p></div></div>`;new bootstrap.Modal(document.getElementById("detailModal")).show();}
function initHome(){fillCategories("filterCategory");renderHomeProducts();document.getElementById("searchInput")?.addEventListener("input",renderHomeProducts);document.getElementById("filterCategory")?.addEventListener("change",renderHomeProducts);}

function saleItems(){try{return JSON.parse(sessionStorage.getItem(CART_KEY)||"[]");}catch{return[];}}
function saveSale(v){sessionStorage.setItem(CART_KEY,JSON.stringify(v));}
function addSaleItem(id){const p=state.products.find(x=>x.id===id&&x.active!==false);if(!p)return;const a=saleItems(),x=a.find(i=>i.id===id);if(x)x.qty++;else a.push({id:p.id,name:p.name,price:p.price,qty:1});saveSale(a);renderSale();}
function updateSaleQty(id,d){const a=saleItems(),x=a.find(i=>i.id===id);if(!x)return;x.qty+=d;saveSale(a.filter(i=>i.qty>0));renderSale();}
function clearSale(){saveSale([]);state.editingOrderId=null;const c=document.getElementById("customerName");if(c)c.value="";const b=document.getElementById("editingOrderBadge");if(b){b.textContent="";b.classList.add("d-none");}renderSale();renderPendingOrders();}
function renderSaleProducts(){const list=document.getElementById("saleProductList");if(!list)return;const q=(document.getElementById("saleSearch")?.value||"").trim().toLowerCase(),cat=document.getElementById("saleCategory")?.value||"all";const ps=state.products.filter(p=>p.active!==false&&p.name.toLowerCase().includes(q)&&(cat==="all"||p.category===cat));list.innerHTML=ps.map(p=>`<div class="col-sm-6 col-xl-4"><div class="card product-card pos-product-card"><div class="product-image-wrap"><img src="${imageSrc(p)}"><span class="product-price-float">${formatMoney(p.price)}</span></div><div class="card-body"><span class="badge badge-category">${escapeHtml(p.category)}</span><h5 class="mt-2 product-name">${escapeHtml(p.name)}</h5><button class="btn btn-warning w-100 mt-2" onclick="addSaleItem(${p.id})"><i class="fa-solid fa-plus me-1"></i>Thêm vào đơn</button></div></div></div>`).join("");}
function renderSale(){const a=saleItems(),box=document.getElementById("saleItems");if(!box)return;const total=a.reduce((s,i)=>s+i.qty*i.price,0);box.innerHTML=a.length?a.map(i=>`<div class="pos-item"><div class="d-flex justify-content-between"><b>${escapeHtml(i.name)}</b><span>${formatMoney(i.price*i.qty)}</span></div><div class="d-flex justify-content-between align-items-center mt-2"><small>${formatMoney(i.price)} x ${i.qty}</small><div class="btn-group btn-group-sm"><button class="btn btn-outline-secondary" onclick="updateSaleQty(${i.id},-1)">-</button><button class="btn btn-light disabled">${i.qty}</button><button class="btn btn-outline-secondary" onclick="updateSaleQty(${i.id},1)">+</button></div></div></div>`).join(""):'<div class="text-muted text-center py-4">Chưa chọn món</div>';document.getElementById("saleTotal").textContent=formatMoney(total);}
function renderPendingOrders(){const box=document.getElementById("pendingOrderList");if(!box)return;const p=state.orders.filter(o=>o.status==="Chờ thanh toán");document.getElementById("pendingOrderCount").textContent=p.length;box.innerHTML=p.length?p.map(o=>`<div class="pending-order-row ${state.editingOrderId===o.id?'active':''}"><div><b>${escapeHtml(o.id)}</b><small>${escapeHtml(o.customer||'Khách lẻ')} • ${fmtDate(o.date)}</small><span>${o.items.map(i=>`${escapeHtml(i.name)} x${i.qty}`).join(', ')}</span></div><div class="text-end"><strong>${formatMoney(o.total)}</strong><button class="btn btn-sm btn-outline-warning mt-1" onclick="loadPendingOrder('${escapeHtml(o.id)}')">Mở đơn</button></div></div>`).join(""):'<div class="text-center text-muted p-3">Không có đơn đang chờ thanh toán.</div>';}
function loadPendingOrder(id){const o=state.orders.find(x=>x.id===id&&x.status==="Chờ thanh toán");if(!o)return;state.editingOrderId=o.id;saveSale(clone(o.items));document.getElementById("customerName").value=o.customer==="Khách lẻ"?"":(o.customer||"");if(o.paymentMethod)document.getElementById("paymentMethod").value=o.paymentMethod;const b=document.getElementById("editingOrderBadge");b.textContent=`Đang mở ${o.id}`;b.classList.remove("d-none");renderSale();renderPendingOrders();scrollTo({top:0,behavior:"smooth"});showToast(`Đã mở đơn ${o.id}`,"info");}
let pendingTransferOrderId=null;
async function saveOrder(paid,forcedId=null){const items=saleItems();if(!items.length){showToast("Chưa có món trong đơn","warning");return null;}const p={id:state.editingOrderId||forcedId||undefined,customer:document.getElementById("customerName").value.trim()||"Khách lẻ",items:clone(items),paymentMethod:document.getElementById("paymentMethod").value,status:paid?"Đã thanh toán":"Chờ thanh toán"};try{const editing=!!state.editingOrderId,r=await apiRequest("orders.php",{method:editing?"PUT":"POST",body:JSON.stringify(p)}),savedId=r.id||p.id;const order={id:savedId,customer:p.customer,total:r.total||items.reduce((s,i)=>s+i.qty*i.price,0)};await refreshCoreData();saveSale([]);state.editingOrderId=null;document.getElementById("customerName").value="";document.getElementById("editingOrderBadge")?.classList.add("d-none");renderSale();renderSaleProducts();renderPendingOrders();showToast(r.message||"Đã lưu đơn");return order;}catch(err){showToast(err.message,"error");return null;}}
function getBankConfig(){try{return JSON.parse(localStorage.getItem(BANK_KEY)||'{"bankCode":"","accountNo":"","accountName":""}');}catch{return{bankCode:"",accountNo:"",accountName:""};}}
function saveBankConfig(){const c={bankCode:document.getElementById("bankCode").value.trim().toUpperCase(),accountNo:document.getElementById("bankAccount").value.trim(),accountName:document.getElementById("bankName").value.trim().toUpperCase()};if(!c.bankCode||!c.accountNo||!c.accountName)return showToast("Hãy nhập đủ thông tin nhận chuyển khoản","warning");localStorage.setItem(BANK_KEY,JSON.stringify(c));renderTransferQr();showToast("Đã lưu cấu hình QR trên thiết bị này");}
function renderTransferQr(){const c=getBankConfig(),total=saleItems().reduce((s,i)=>s+i.qty*i.price,0),img=document.getElementById("transferQrImage"),empty=document.getElementById("transferQrEmpty"),err=document.getElementById("transferQrError");if(!img)return;document.getElementById("bankCode").value=c.bankCode||"";document.getElementById("bankAccount").value=c.accountNo||"";document.getElementById("bankName").value=c.accountName||"";document.getElementById("transferAmount").textContent=formatMoney(total);document.getElementById("transferOrderCode").textContent=pendingTransferOrderId||"-";err.classList.add("d-none");if(!c.bankCode||!c.accountNo||!c.accountName){img.classList.add("d-none");empty.classList.remove("d-none");return;}const info=`CAFFE MINI ${pendingTransferOrderId||"THANH TOAN"}`;img.src=`https://img.vietqr.io/image/${encodeURIComponent(c.bankCode)}-${encodeURIComponent(c.accountNo)}-compact2.png?amount=${Math.round(total)}&addInfo=${encodeURIComponent(info)}&accountName=${encodeURIComponent(c.accountName)}`;empty.classList.add("d-none");img.classList.remove("d-none");img.onerror=()=>{img.classList.add("d-none");empty.classList.remove("d-none");err.classList.remove("d-none");};img.onload=()=>err.classList.add("d-none");}
function openTransferPayment(){if(!saleItems().length)return showToast("Chưa có món trong đơn","warning");pendingTransferOrderId=state.editingOrderId||("DH"+Date.now());renderTransferQr();new bootstrap.Modal(document.getElementById("transferQrModal")).show();}
function openReviewModal(o){if(!o)return;document.getElementById("reviewOrderId").value=o.id;document.getElementById("reviewOrderCode").textContent=o.id;document.getElementById("reviewCustomer").value=o.customer&&o.customer!=="Khách lẻ"?o.customer:"";document.getElementById("reviewRating").value="5";document.getElementById("reviewContent").value="";new bootstrap.Modal(document.getElementById("reviewModal")).show();}
async function confirmTransferPayment(){const c=getBankConfig();if(!c.bankCode||!c.accountNo||!c.accountName)return showToast("Chưa cấu hình tài khoản nhận chuyển khoản","warning");const o=await saveOrder(true,pendingTransferOrderId);if(!o)return;pendingTransferOrderId=null;bootstrap.Modal.getInstance(document.getElementById("transferQrModal"))?.hide();setTimeout(()=>openReviewModal(o),250);}
async function handlePayNow(){if(document.getElementById("paymentMethod").value==="Chuyển khoản")openTransferPayment();else{const o=await saveOrder(true);if(o)openReviewModal(o);}}
async function saveReview(){const p={orderId:document.getElementById("reviewOrderId").value.trim(),customer:document.getElementById("reviewCustomer").value.trim()||"Khách hàng",rating:Number(document.getElementById("reviewRating").value),content:document.getElementById("reviewContent").value.trim()};try{const r=await apiRequest("reviews.php",{method:"POST",body:JSON.stringify(p)});await refreshCoreData();bootstrap.Modal.getInstance(document.getElementById("reviewModal"))?.hide();showToast(r.message||"Đã ghi nhận đánh giá");}catch(err){showToast(err.message,"error");}}
function initSell(){const u=requireLogin(["admin","staff"]);if(!u)return;document.getElementById("staffName").textContent=u.fullName;if(u.role==="admin")document.getElementById("navAdminItem")?.classList.remove("d-none");fillCategories("saleCategory");renderSaleProducts();renderSale();renderPendingOrders();document.getElementById("saleSearch").addEventListener("input",renderSaleProducts);document.getElementById("saleCategory").addEventListener("change",renderSaleProducts);document.getElementById("clearSaleBtn").onclick=clearSale;document.getElementById("saveUnpaidBtn").onclick=()=>saveOrder(false);document.getElementById("payNowBtn").onclick=handlePayNow;document.getElementById("saveReviewBtn").onclick=saveReview;document.getElementById("saveBankConfigBtn").onclick=saveBankConfig;document.getElementById("confirmTransferBtn").onclick=confirmTransferPayment;}

function initProfile(){const u=requireLogin(["admin","staff"]);if(!u)return;if(u.role==="admin")document.getElementById("navAdminItem")?.classList.remove("d-none");document.getElementById("profileUsername").value=u.username;document.getElementById("profileName").value=u.fullName;document.getElementById("profileEmail").value=u.email;document.getElementById("profilePhone").value=u.phone||"";document.getElementById("profileForm").addEventListener("submit",async e=>{e.preventDefault();try{const r=await apiRequest("profile.php",{method:"PUT",body:JSON.stringify({fullName:document.getElementById("profileName").value.trim(),email:document.getElementById("profileEmail").value.trim(),phone:document.getElementById("profilePhone").value.trim(),password:document.getElementById("profilePass").value})});state.currentUser=r.user;document.getElementById("profilePass").value="";showToast(r.message||"Đã cập nhật thông tin");}catch(err){showToast(err.message,"error");}});}

function statusBadge(s){return s==="Đã thanh toán"?"badge-status-paid":s==="Hủy"?"badge-status-cancelled":"badge-status-unpaid";}
function paidOrders(){return state.orders.filter(o=>o.status==="Đã thanh toán");}
function renderDashboard(){const paid=paidOrders();document.getElementById("statRevenue").textContent=formatMoney(paid.reduce((s,o)=>s+o.total,0));document.getElementById("statOrders").textContent=state.orders.length;document.getElementById("statUsers").textContent=state.users.filter(u=>u.role==="staff").length;document.getElementById("statProducts").textContent=state.products.length;document.getElementById("recentOrders").innerHTML=state.orders.slice(0,6).map(o=>`<tr><td><b>${escapeHtml(o.id)}</b></td><td>${escapeHtml(o.customer)}</td><td>${escapeHtml(o.staffName)}</td><td>${formatMoney(o.total)}</td><td><span class="badge ${statusBadge(o.status)}">${escapeHtml(o.status)}</span></td><td>${fmtDate(o.date)}</td></tr>`).join("")||'<tr><td colspan="6" class="text-center text-muted">Chưa có đơn hàng</td></tr>';}
function renderAdminProducts(){document.getElementById("productTbody").innerHTML=state.products.map(p=>`<tr><td><img class="thumb" src="${p.image||''}"></td><td><b>${p.name}</b></td><td>${p.category}</td><td>${formatMoney(p.price)}</td><td><b>${Number(p.totalQuantity??p.stock??0)}</b></td><td><span class="badge bg-primary">${Number(p.sold??0)}</span></td><td><span class="badge ${Number(p.remaining??0)<=10?'bg-danger':'bg-success'}">${Number(p.remaining??0)}</span></td><td>${p.active!==false?'<span class="badge bg-success">Đang bán</span>':'<span class="badge bg-secondary">Tạm ẩn</span>'}</td><td><button class="btn btn-sm btn-primary" onclick="editProduct(${p.id})"><i class="fa-solid fa-pen"></i></button> <button class="btn btn-sm btn-danger" onclick="deleteProduct(${p.id})"><i class="fa-solid fa-trash"></i></button></td></tr>`).join("");}
function resetProductForm(){document.getElementById("productForm").reset();document.getElementById("pId").value="";document.getElementById("productFormTitle").textContent="Thêm món";document.getElementById("pCancelBtn").classList.add("d-none");}
function editProduct(id){const p=state.products.find(x=>x.id===id);document.getElementById("pStock").value=p.stock??100;if(!p)return;document.getElementById("pId").value=p.id;document.getElementById("pName").value=p.name;document.getElementById("pCategory").value=p.category;document.getElementById("pPrice").value=p.price;document.getElementById("pActive").value=String(p.active!==false);document.getElementById("pImage").value=p.image||"";document.getElementById("pDesc").value=p.desc||"";document.getElementById("productFormTitle").textContent="Cập nhật món";document.getElementById("pCancelBtn").classList.remove("d-none");}
async function saveProduct(e){e.preventDefault();const id=Number(document.getElementById("pId").value||0),p={id,name:document.getElementById("pName").value.trim(),category:document.getElementById("pCategory").value.trim(),price:Number(document.getElementById("pPrice").value),stock:Number(document.getElementById("pStock").value||0),active:document.getElementById("pActive").value==="true",image:document.getElementById("pImage").value.trim(),desc:document.getElementById("pDesc").value.trim()};try{const r=await apiRequest("products.php",{method:id?"PUT":"POST",body:JSON.stringify(p)});await refreshCoreData();resetProductForm();renderAdminProducts();renderDashboard();showToast(r.message||"Đã lưu món");}catch(err){showToast(err.message,"error");}}
async function deleteProduct(id){if(!confirm("Xóa món này? Nếu món đã có trong hóa đơn, hệ thống sẽ chuyển sang Tạm ẩn."))return;try{const r=await apiRequest(`products.php?id=${id}`,{method:"DELETE"});await refreshCoreData();renderAdminProducts();renderDashboard();showToast(r.message||"Đã cập nhật món","info");}catch(err){showToast(err.message,"error");}}
function renderOrders(){document.getElementById("orderTbody").innerHTML=state.orders.map(o=>`<tr><td><b>${escapeHtml(o.id)}</b><br><small>${fmtDate(o.date)}</small></td><td>${escapeHtml(o.customer)}</td><td>${escapeHtml(o.staffName)}</td><td>${o.items.map(i=>`${escapeHtml(i.name)} x${i.qty}`).join("<br>")}</td><td>${formatMoney(o.total)}</td><td>${escapeHtml(o.paymentMethod||"-")}</td><td><span class="badge ${statusBadge(o.status)}">${escapeHtml(o.status)}</span></td><td><select class="form-select form-select-sm" onchange="updateOrderStatus('${escapeHtml(o.id)}',this.value)"><option ${o.status==="Chờ thanh toán"?"selected":""}>Chờ thanh toán</option><option ${o.status==="Đã thanh toán"?"selected":""}>Đã thanh toán</option><option ${o.status==="Hủy"?"selected":""}>Hủy</option></select></td></tr>`).join("")||'<tr><td colspan="8" class="text-center text-muted">Chưa có đơn hàng</td></tr>';}
async function updateOrderStatus(id,status){try{const r=await apiRequest("orders.php",{method:"PUT",body:JSON.stringify({action:"status",id,status})});await refreshCoreData();renderOrders();renderDashboard();renderRevenue();showToast(r.message||"Đã cập nhật trạng thái");}catch(err){showToast(err.message,"error");}}
function renderUsers(){document.getElementById("userTbody").innerHTML=state.users.map(u=>`<tr><td><b>${escapeHtml(u.username)}</b></td><td>${escapeHtml(u.fullName)}</td><td>${escapeHtml(u.email)}</td><td>${u.role==="admin"?"Admin":"Nhân viên"}</td><td>${u.active!==false?'<span class="badge bg-success">Hoạt động</span>':'<span class="badge bg-secondary">Đã khóa</span>'}</td><td><button class="btn btn-sm btn-primary" onclick="editUser('${escapeHtml(u.username)}')"><i class="fa-solid fa-pen"></i></button> <button class="btn btn-sm btn-warning" onclick="toggleUser('${escapeHtml(u.username)}')" ${u.username==='admin'?'disabled':''}><i class="fa-solid fa-lock"></i></button> <button class="btn btn-sm btn-danger" onclick="deleteUser('${escapeHtml(u.username)}')" ${u.username==='admin'?'disabled':''}><i class="fa-solid fa-trash"></i></button></td></tr>`).join("");}
function resetUserForm(){document.getElementById("userForm").reset();document.getElementById("uOriginal").value="";document.getElementById("uActive").value="true";document.getElementById("uRole").value="staff";document.getElementById("uCancelBtn").classList.add("d-none");}
function editUser(username){const u=state.users.find(x=>x.username===username);if(!u)return;document.getElementById("uOriginal").value=u.username;document.getElementById("uUsername").value=u.username;document.getElementById("uName").value=u.fullName;document.getElementById("uEmail").value=u.email;document.getElementById("uPhone").value=u.phone||"";document.getElementById("uPass").value="";document.getElementById("uRole").value=u.role;document.getElementById("uActive").value=String(u.active!==false);document.getElementById("uCancelBtn").classList.remove("d-none");}
async function saveUser(e){e.preventDefault();const original=document.getElementById("uOriginal").value,p={original,username:document.getElementById("uUsername").value.trim(),fullName:document.getElementById("uName").value.trim(),email:document.getElementById("uEmail").value.trim(),phone:document.getElementById("uPhone").value.trim(),role:document.getElementById("uRole").value,active:document.getElementById("uActive").value==="true",password:document.getElementById("uPass").value};try{const r=await apiRequest("users.php",{method:original?"PUT":"POST",body:JSON.stringify(p)});await refreshCoreData();resetUserForm();renderUsers();renderDashboard();showToast(r.message||"Đã lưu tài khoản");}catch(err){showToast(err.message,"error");}}
async function toggleUser(username){if(username==="admin")return;try{const r=await apiRequest("users.php",{method:"PATCH",body:JSON.stringify({username})});await refreshCoreData();renderUsers();renderDashboard();showToast(r.message||"Đã cập nhật trạng thái","info");}catch(err){showToast(err.message,"error");}}
async function deleteUser(username){if(username==="admin"||!confirm("Xóa tài khoản này?"))return;try{const r=await apiRequest(`users.php?username=${encodeURIComponent(username)}`,{method:"DELETE"});await refreshCoreData();renderUsers();renderDashboard();showToast(r.message||"Đã xóa tài khoản","info");}catch(err){showToast(err.message,"error");}}
function renderReviews(){document.getElementById("reviewTbody").innerHTML=state.reviews.map(r=>`<tr><td><b>${escapeHtml(r.orderId||"-")}</b></td><td>${escapeHtml(r.customer)}</td><td><span class="review-stars">${"★".repeat(r.rating)}${"☆".repeat(5-r.rating)}</span></td><td>${escapeHtml(r.content||"")}</td><td>${escapeHtml(r.enteredBy)}</td><td>${fmtDate(r.date)}</td><td><button class="btn btn-sm btn-danger" onclick="deleteReview('${escapeHtml(r.id)}')"><i class="fa-solid fa-trash"></i></button></td></tr>`).join("")||'<tr><td colspan="7" class="text-center text-muted">Chưa có đánh giá</td></tr>';}
async function deleteReview(id){if(!confirm("Xóa đánh giá này?"))return;try{const r=await apiRequest(`reviews.php?id=${encodeURIComponent(id)}`,{method:"DELETE"});await refreshCoreData();renderReviews();showToast(r.message||"Đã xóa đánh giá","info");}catch(err){showToast(err.message,"error");}}
function renderRevenue(){const from=document.getElementById("revFrom")?.value,to=document.getElementById("revTo")?.value;let os=paidOrders();if(from)os=os.filter(o=>String(o.date).slice(0,10)>=from);if(to)os=os.filter(o=>String(o.date).slice(0,10)<=to);document.getElementById("revTotal").textContent=formatMoney(os.reduce((s,o)=>s+o.total,0));document.getElementById("revOrderCount").textContent=os.length;const g={};os.forEach(o=>{const d=String(o.date).slice(0,10);g[d]??={count:0,total:0};g[d].count++;g[d].total+=o.total;});document.getElementById("revenueTbody").innerHTML=Object.keys(g).sort().reverse().map(d=>`<tr><td>${d.split("-").reverse().join("/")}</td><td>${g[d].count}</td><td class="text-danger fw-bold">${formatMoney(g[d].total)}</td></tr>`).join("")||'<tr><td colspan="3" class="text-center text-muted">Chưa có dữ liệu</td></tr>';}
function initAdmin(){const u=requireLogin(["admin"]);if(!u)return;document.getElementById("adminName").textContent=u.fullName;renderDashboard();renderAdminProducts();renderOrders();renderUsers();renderReviews();renderRevenue();document.getElementById("productForm").addEventListener("submit",saveProduct);document.getElementById("pCancelBtn").onclick=resetProductForm;document.getElementById("userForm").addEventListener("submit",saveUser);document.getElementById("uCancelBtn").onclick=resetUserForm;document.getElementById("filterRevenueBtn").onclick=renderRevenue;}

function aiNormalize(s=""){return s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/đ/g,"d");}
function aiProductMatch(q){const nq=aiNormalize(q);let best=null,score=0;state.products.filter(p=>p.active!==false).forEach(p=>{const t=aiNormalize(p.name).split(/\s+/).filter(x=>x.length>1),s=t.filter(x=>nq.includes(x)).length;if(s>score){score=s;best=p;}});return score?best:null;}
function aiReply(text){const q=aiNormalize(text),ps=state.products.filter(p=>p.active!==false),u=state.currentUser;if(!q.trim())return"Bạn hãy nhập câu hỏi nhé.";if(/xin chao|chao|hello|hi\b/.test(q))return"Chào bạn! Tôi là Trợ lý Caffe Mini. Bạn có thể hỏi về menu, giá món hoặc thanh toán.";if(/menu|thuc don|co mon gi|ban gi/.test(q))return`Caffe Mini hiện có ${ps.length} món thuộc các nhóm: ${[...new Set(ps.map(p=>p.category))].join(", ")}.`;if(/thanh toan|chuyen khoan|qr|tien mat/.test(q))return"Caffe Mini hỗ trợ Tiền mặt và Chuyển khoản QR.";if(/doanh thu/.test(q)){if(u?.role!=="admin")return"Thông tin doanh thu chỉ hiển thị cho Admin.";return`Tổng doanh thu từ đơn đã thanh toán: ${formatMoney(paidOrders().reduce((s,o)=>s+o.total,0))}.`;}const p=aiProductMatch(q);if(p)return`${p.name} thuộc nhóm ${p.category}, giá ${formatMoney(p.price)}. ${p.desc||""}`;return"Bạn thử hỏi về menu, giá món hoặc thanh toán nhé.";}
function addAiMessage(text,who="bot"){const b=document.getElementById("aiMessages");if(!b)return;const e=document.createElement("div");e.className=`ai-msg ${who}`;e.textContent=text;b.appendChild(e);b.scrollTop=b.scrollHeight;}
function sendAiMessage(){const i=document.getElementById("aiInput");if(!i)return;const t=i.value.trim();if(!t)return;addAiMessage(t,"user");i.value="";setTimeout(()=>addAiMessage(aiReply(t),"bot"),150);}
function initAiChatWidget(){if(document.getElementById("aiChatWidget"))return;document.body.insertAdjacentHTML("beforeend",`<button class="ai-fab" id="aiFab"><i class="fa-solid fa-robot"></i></button><div class="ai-widget" id="aiChatWidget"><div class="ai-head"><div><b><i class="fa-solid fa-robot me-1"></i>Trợ lý Caffe Mini</b><small>Hỗ trợ tự động • nội bộ</small></div><button class="btn-close btn-close-white" id="aiClose"></button></div><div class="ai-messages" id="aiMessages"></div><div class="ai-quick"><button data-q="Menu có những gì?">Menu</button><button data-q="Nước ép có gì?">Nước ép</button><button data-q="Thanh toán QR thế nào?">QR</button></div><div class="ai-input"><input id="aiInput" placeholder="Hỏi Caffe Mini..."/><button id="aiSend"><i class="fa-solid fa-paper-plane"></i></button></div></div>`);const w=document.getElementById("aiChatWidget");document.getElementById("aiFab").onclick=()=>{w.classList.add("open");if(!document.getElementById("aiMessages").children.length)addAiMessage("Chào bạn! Tôi có thể tư vấn menu, giá món và hướng dẫn thanh toán.");};document.getElementById("aiClose").onclick=()=>w.classList.remove("open");document.getElementById("aiSend").onclick=sendAiMessage;document.getElementById("aiInput").addEventListener("keydown",e=>{if(e.key==="Enter")sendAiMessage();});document.querySelectorAll(".ai-quick button").forEach(b=>b.onclick=()=>{document.getElementById("aiInput").value=b.dataset.q;sendAiMessage();});}
