<?php
require __DIR__.'/common.php';$d=json_input();$action=(string)($d['action']??$_GET['action']??'me');
try{
 if($action==='me')respond(['ok'=>true,'user'=>current_user($pdo),'csrfToken'=>csrf_token()]);
 check_csrf();
 if($action==='login'){$id=trim((string)($d['id']??''));$pass=(string)($d['password']??'');if($id===''||$pass==='')respond(['ok'=>false,'message'=>'Hãy nhập đầy đủ tài khoản và mật khẩu.'],422);$s=$pdo->prepare('SELECT user_id,username,password,active FROM users WHERE username=? OR email=? LIMIT 1');$s->execute([$id,$id]);$u=$s->fetch();if(!$u||!password_verify($pass,$u['password']))respond(['ok'=>false,'message'=>'Sai tên đăng nhập hoặc mật khẩu.'],401);if(!(bool)$u['active'])respond(['ok'=>false,'message'=>'Tài khoản đã bị khóa.'],403);session_regenerate_id(true);$_SESSION['user_id']=(int)$u['user_id'];$_SESSION['csrf']=bin2hex(random_bytes(24));respond(['ok'=>true,'user'=>current_user($pdo),'csrfToken'=>csrf_token()]);}
 if($action==='register'){$username=trim((string)($d['username']??''));$email=trim((string)($d['email']??''));$name=trim((string)($d['fullName']??''));$phone=trim((string)($d['phone']??''));$pass=(string)($d['password']??'');if(!preg_match('/^[A-Za-z0-9_.-]{3,50}$/',$username))respond(['ok'=>false,'message'=>'Tên đăng nhập phải có 3-50 ký tự và không chứa khoảng trắng.'],422);if(!filter_var($email,FILTER_VALIDATE_EMAIL))respond(['ok'=>false,'message'=>'Email không hợp lệ.'],422);if($name===''||mb_strlen($name)>100)respond(['ok'=>false,'message'=>'Họ tên không hợp lệ.'],422);if(strlen($pass)<5)respond(['ok'=>false,'message'=>'Mật khẩu phải có ít nhất 5 ký tự.'],422);$c=$pdo->prepare('SELECT COUNT(*) FROM users WHERE username=? OR email=?');$c->execute([$username,$email]);if((int)$c->fetchColumn()>0)respond(['ok'=>false,'message'=>'Tên đăng nhập hoặc email đã tồn tại.'],409);$s=$pdo->prepare('INSERT INTO users(username,password,full_name,email,phone,role,active) VALUES(?,?,?,?,?,"staff",1)');$s->execute([$username,password_hash($pass,PASSWORD_DEFAULT),$name,$email,$phone]);respond(['ok'=>true,'message'=>'Đăng ký thành công.']);}
 if($action==='logout'){$_SESSION=[];if(ini_get('session.use_cookies')){$p=session_get_cookie_params();setcookie(session_name(),'',time()-42000,$p['path'],$p['domain'],$p['secure'],$p['httponly']);}session_destroy();respond(['ok'=>true]);}
 respond(['ok'=>false,'message'=>'Yêu cầu xác thực không hợp lệ.'],400);
}catch(Throwable $e){error_log($e->__toString());respond(['ok'=>false,'message'=>'Có lỗi khi xử lý tài khoản.'],500);}
